stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .maven-settings.xml --batch-mode"

build:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn clean compile

test:
  stage: test
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn test

deploy:
  stage: deploy
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - mvn package
    - echo "Spring Boot App built and ready!"